/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1PersistentVolumeClaimCondition (
  /* Last time we probed the condition. */
  lastProbeTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Last time the condition transitioned from one status to another. */
  lastTransitionTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Human-readable message indicating details about last transition. */
  message: Option[String],
  /* Unique, this should be a short, machine understandable string that gives the reason for condition's last transition. If it reports \"ResizeStarted\" that means the underlying persistent volume is being resized. */
  reason: Option[String],
  status: String,
  _type: String
)

