/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAuthenticationV1TokenReviewStatus (
  /* Authenticated indicates that the token was associated with a known user. */
  authenticated: Option[Boolean],
  /* Error indicates that the token couldn't be checked */
  error: Option[String],
  /* User is the UserInfo associated with the provided token. */
  user: Option[IoK8sApiAuthenticationV1UserInfo]
) extends ApiModel


