/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1LimitRangeItem (
  /* Default resource requirement limit value by resource name if resource limit is omitted. */
  default: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* DefaultRequest is the default resource requirement request value by resource name if resource request is omitted. */
  defaultRequest: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* Max usage constraints on this kind by resource name. */
  max: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* MaxLimitRequestRatio if specified, the named resource must have a request and limit that are both non-zero where limit divided by request is less than or equal to the enumerated value; this represents the max burst for the named resource. */
  maxLimitRequestRatio: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* Min usage constraints on this kind by resource name. */
  min: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* Type of resource that this limit applies to. */
  _type: Option[String]
)

