/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAuthenticationV1TokenReviewStatus (
  /* Authenticated indicates that the token was associated with a known user. */
  authenticated: Option[Boolean],
  /* Error indicates that the token couldn't be checked */
  error: Option[String],
  /* User is the UserInfo associated with the provided token. */
  user: Option[IoK8sApiAuthenticationV1UserInfo]
)

