/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApimachineryPkgApisMetaV1APIResource (
  /* categories is a list of the grouped resources this resource belongs to (e.g. 'all') */
  categories: Option[List[String]],
  /* group is the preferred group of the resource.  Empty implies the group of the containing resource list. For subresources, this may have a different value, for example: Scale\". */
  group: Option[String],
  /* kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo') */
  kind: String,
  /* name is the plural name of the resource. */
  name: String,
  /* namespaced indicates if a resource is namespaced or not. */
  namespaced: Boolean,
  /* shortNames is a list of suggested short names of the resource. */
  shortNames: Option[List[String]],
  /* singularName is the singular name of the resource.  This allows clients to handle plural and singular opaquely. The singularName is more correct for reporting status on a single item and both singular and plural are allowed from the kubectl CLI interface. */
  singularName: String,
  /* verbs is a list of supported kube verbs (this includes get, list, watch, create, update, patch, delete, deletecollection, and proxy) */
  verbs: List[String],
  /* version is the preferred version of the resource.  Empty implies the version of the containing resource list For subresources, this may have a different value, for example: v1 (while inside a v1beta1 version of the core resource's group)\". */
  version: Option[String]
)

