/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiSettingsV1alpha1PodPresetSpec (
  /* Env defines the collection of EnvVar to inject into containers. */
  env: Option[List[IoK8sApiCoreV1EnvVar]],
  /* EnvFrom defines the collection of EnvFromSource to inject into containers. */
  envFrom: Option[List[IoK8sApiCoreV1EnvFromSource]],
  /* Selector is a label query over a set of resources, in this case pods. Required. */
  selector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector],
  /* VolumeMounts defines the collection of VolumeMount to inject into containers. */
  volumeMounts: Option[List[IoK8sApiCoreV1VolumeMount]],
  /* Volumes defines the collection of Volume to inject into the pod. */
  volumes: Option[List[IoK8sApiCoreV1Volume]]
)

