/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery (
  /* groupVersion specifies the API group and version in the form \"group/version\" */
  groupVersion: String,
  /* version specifies the version in the form of \"version\". This is to save the clients the trouble of splitting the GroupVersion. */
  version: String
) extends ApiModel


