/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAppsV1beta1DeploymentSpec (
  /* Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) */
  minReadySeconds: Option[Integer],
  /* Indicates that the deployment is paused. */
  paused: Option[Boolean],
  /* The maximum time in seconds for a deployment to make progress before it is considered to be failed. The deployment controller will continue to process failed deployments and a condition with a ProgressDeadlineExceeded reason will be surfaced in the deployment status. Note that progress will not be estimated during the time a deployment is paused. Defaults to 600s. */
  progressDeadlineSeconds: Option[Integer],
  /* Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. */
  replicas: Option[Integer],
  /* The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 2. */
  revisionHistoryLimit: Option[Integer],
  /* DEPRECATED. The config this deployment is rolling back to. Will be cleared after rollback is done. */
  rollbackTo: Option[IoK8sApiAppsV1beta1RollbackConfig],
  /* Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment. */
  selector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector],
  /* The deployment strategy to use to replace existing pods with new ones. */
  strategy: Option[IoK8sApiAppsV1beta1DeploymentStrategy],
  /* Template describes the pods that will be created. */
  template: IoK8sApiCoreV1PodTemplateSpec
)

