/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1PreferredSchedulingTerm (
  /* A node selector term, associated with the corresponding weight. */
  preference: IoK8sApiCoreV1NodeSelectorTerm,
  /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
  weight: Integer
)

