/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition (
  /* timestamp for the last update to this condition */
  lastUpdateTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* human readable message with details about the request state */
  message: Option[String],
  /* brief reason for the request state */
  reason: Option[String],
  /* request approval state, currently Approved or Denied. */
  _type: String
)

