/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAppsV1beta2StatefulSetUpdateStrategy (
  /* RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType. */
  rollingUpdate: Option[IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategy],
  /* Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate. */
  `type`: Option[String]
) extends ApiModel


