/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1WeightedPodAffinityTerm (
  /* Required. A pod affinity term, associated with the corresponding weight. */
  podAffinityTerm: IoK8sApiCoreV1PodAffinityTerm,
  /* weight associated with matching the corresponding podAffinityTerm, in the range 1-100. */
  weight: Int
) extends ApiModel


