/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiNetworkingV1NetworkPolicyPort (
  /* The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. */
  port: Option[IoK8sApimachineryPkgUtilIntstrIntOrString],
  /* The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP. */
  protocol: Option[String]
) extends ApiModel


