/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAutoscalingV2beta1ObjectMetricSource (
  /* metricName is the name of the metric in question. */
  metricName: String,
  /* target is the described Kubernetes object. */
  target: IoK8sApiAutoscalingV2beta1CrossVersionObjectReference,
  /* targetValue is the target value of the metric (as a quantity). */
  targetValue: IoK8sApimachineryPkgApiResourceQuantity
)

