/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiSettingsV1alpha1PodPresetSpec (
  /* Env defines the collection of EnvVar to inject into containers. */
  env: Option[Seq[IoK8sApiCoreV1EnvVar]],
  /* EnvFrom defines the collection of EnvFromSource to inject into containers. */
  envFrom: Option[Seq[IoK8sApiCoreV1EnvFromSource]],
  /* Selector is a label query over a set of resources, in this case pods. Required. */
  selector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector],
  /* VolumeMounts defines the collection of VolumeMount to inject into containers. */
  volumeMounts: Option[Seq[IoK8sApiCoreV1VolumeMount]],
  /* Volumes defines the collection of Volume to inject into the pod. */
  volumes: Option[Seq[IoK8sApiCoreV1Volume]]
) extends ApiModel


