/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1ContainerStateTerminated (
  /* Container's ID in the format 'docker://<container_id>' */
  containerID: Option[String],
  /* Exit status from the last termination of the container */
  exitCode: Integer,
  /* Time at which the container last terminated */
  finishedAt: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Message regarding the last termination of the container */
  message: Option[String],
  /* (brief) reason from the last termination of the container */
  reason: Option[String],
  /* Signal from the last termination of the container */
  signal: Option[Integer],
  /* Time at which previous execution of the container started */
  startedAt: Option[IoK8sApimachineryPkgApisMetaV1Time]
)

