/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAdmissionregistrationV1alpha1ExternalAdmissionHook (
  /* ClientConfig defines how to communicate with the hook. Required */
  clientConfig: IoK8sApiAdmissionregistrationV1alpha1AdmissionHookClientConfig,
  /* FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Ignore. */
  failurePolicy: Option[String],
  /* The name of the external admission webhook. Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where \"imagepolicy\" is the name of the webhook, and kubernetes.io is the name of the organization. Required. */
  name: String,
  /* Rules describes what operations on what resources/subresources the webhook cares about. The webhook cares about an operation if it matches _any_ Rule. */
  rules: Option[List[IoK8sApiAdmissionregistrationV1alpha1RuleWithOperations]]
)

