/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAppsV1beta2DaemonSetUpdateStrategy (
  /* Rolling update config params. Present only if type = \"RollingUpdate\". */
  rollingUpdate: Option[IoK8sApiAppsV1beta2RollingUpdateDaemonSet],
  /* Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate. */
  `type`: Option[String]
) extends ApiModel


