/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1ComponentCondition (
  /* Condition error code for a component. For example, a health check error code. */
  error: Option[String],
  /* Message about the condition for a component. For example, information about a health check. */
  message: Option[String],
  /* Status of the condition for a component. Valid values for \"Healthy\": \"True\", \"False\", or \"Unknown\". */
  status: String,
  /* Type of condition for a component. Valid value: \"Healthy\" */
  `type`: String
) extends ApiModel


