/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1PersistentVolumeClaimSpec (
  /* AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
  accessModes: Option[Seq[String]],
  /* Resources represents the minimum resources the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources */
  resources: Option[IoK8sApiCoreV1ResourceRequirements],
  /* A label query over volumes to consider for binding. */
  selector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector],
  /* Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1 */
  storageClassName: Option[String],
  /* VolumeName is the binding reference to the PersistentVolume backing this claim. */
  volumeName: Option[String]
) extends ApiModel


