/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAdmissionregistrationV1alpha1AdmissionHookClientConfig (
  /* CABundle is a PEM encoded CA bundle which will be used to validate webhook's server certificate. Required */
  caBundle: Array[Byte],
  /* Service is a reference to the service for this webhook. If there is only one port open for the service, that port will be used. If there are multiple ports open, port 443 will be used if it is open, otherwise it is an error. Required */
  service: IoK8sApiAdmissionregistrationV1alpha1ServiceReference
) extends ApiModel


