/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiBatchV2alpha1CronJobStatus (
  /* A list of pointers to currently running jobs. */
  active: Option[List[IoK8sApiCoreV1ObjectReference]],
  /* Information when was the last time the job was successfully scheduled. */
  lastScheduleTime: Option[IoK8sApimachineryPkgApisMetaV1Time]
)

