/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1ContainerStatus (
  /* Container's ID in the format 'docker://<container_id>'. */
  containerID: Option[String],
  /* The image the container is running. More info: https://kubernetes.io/docs/concepts/containers/images */
  image: String,
  /* ImageID of the container's image. */
  imageID: String,
  /* Details about the container's last termination condition. */
  lastState: Option[IoK8sApiCoreV1ContainerState],
  /* This must be a DNS_LABEL. Each container in a pod must have a unique name. Cannot be updated. */
  name: String,
  /* Specifies whether the container has passed its readiness probe. */
  ready: Boolean,
  /* The number of times the container has been restarted, currently based on the number of dead containers that have not yet been removed. Note that this is calculated from dead containers. But those containers are subject to garbage collection. This value will get capped at 5 by GC. */
  restartCount: Integer,
  /* Details about the container's current condition. */
  state: Option[IoK8sApiCoreV1ContainerState]
)

