/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1EnvVarSource (
  /* Selects a key of a ConfigMap. */
  configMapKeyRef: Option[IoK8sApiCoreV1ConfigMapKeySelector],
  /* Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP. */
  fieldRef: Option[IoK8sApiCoreV1ObjectFieldSelector],
  /* Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported. */
  resourceFieldRef: Option[IoK8sApiCoreV1ResourceFieldSelector],
  /* Selects a key of a secret in the pod's namespace */
  secretKeyRef: Option[IoK8sApiCoreV1SecretKeySelector]
)

