/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1EndpointAddress (
  /* The Hostname of this endpoint */
  hostname: Option[String],
  /* The IP of this endpoint. May not be loopback (127.0.0.0/8), link-local (169.254.0.0/16), or link-local multicast ((224.0.0.0/24). IPv6 is also accepted but not fully supported on all platforms. Also, certain kubernetes components, like kube-proxy, are not IPv6 ready. */
  ip: String,
  /* Optional: Node hosting this endpoint. This can be used to determine endpoints local to a node. */
  nodeName: Option[String],
  /* Reference to object providing the endpoint. */
  targetRef: Option[IoK8sApiCoreV1ObjectReference]
) extends ApiModel


