/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiExtensionsV1beta1SELinuxStrategyOptions (
  /* type is the strategy that will dictate the allowable labels that may be set. */
  rule: String,
  /* seLinuxOptions required to run as; required for MustRunAs More info: https://git.k8s.io/community/contributors/design-proposals/security_context.md */
  seLinuxOptions: Option[IoK8sApiCoreV1SELinuxOptions]
) extends ApiModel


