/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition (
  /* timestamp for the last update to this condition */
  lastUpdateTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* human readable message with details about the request state */
  message: Option[String],
  /* brief reason for the request state */
  reason: Option[String],
  /* request approval state, currently Approved or Denied. */
  `type`: String
) extends ApiModel


