/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiNetworkingV1NetworkPolicyPort (
  /* The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers. */
  port: Option[IoK8sApimachineryPkgUtilIntstrIntOrString],
  /* The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP. */
  protocol: Option[String]
)

