/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAutoscalingV1CrossVersionObjectReference (
  /* API version of the referent */
  apiVersion: Option[String],
  /* Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds\" */
  kind: String,
  /* Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names */
  name: String
) extends ApiModel


