/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1PreferredSchedulingTerm (
  /* A node selector term, associated with the corresponding weight. */
  preference: IoK8sApiCoreV1NodeSelectorTerm,
  /* Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100. */
  weight: Int
) extends ApiModel


