/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiExtensionsV1beta1HTTPIngressRuleValue (
  /* A collection of paths that map requests to backends. */
  paths: Seq[IoK8sApiExtensionsV1beta1HTTPIngressPath]
) extends ApiModel


