/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiExtensionsV1beta1RunAsUserStrategyOptions (
  /* Ranges are the allowed ranges of uids that may be used. */
  ranges: Option[List[IoK8sApiExtensionsV1beta1IDRange]],
  /* Rule is the strategy that will dictate the allowable RunAsUser values that may be set. */
  rule: String
)

