/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps (
  ref: Option[String],
  schema: Option[String],
  additionalItems: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool],
  additionalProperties: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool],
  allOf: Option[List[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  anyOf: Option[List[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  default: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON],
  definitions: Option[Map[String, IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  dependencies: Option[Map[String, IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray]],
  description: Option[String],
  enum: Option[List[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON]],
  example: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON],
  exclusiveMaximum: Option[Boolean],
  exclusiveMinimum: Option[Boolean],
  externalDocs: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation],
  format: Option[String],
  id: Option[String],
  items: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray],
  maxItems: Option[Long],
  maxLength: Option[Long],
  maxProperties: Option[Long],
  maximum: Option[Double],
  minItems: Option[Long],
  minLength: Option[Long],
  minProperties: Option[Long],
  minimum: Option[Double],
  multipleOf: Option[Double],
  not: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps],
  oneOf: Option[List[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  pattern: Option[String],
  patternProperties: Option[Map[String, IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  properties: Option[Map[String, IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]],
  required: Option[List[String]],
  title: Option[String],
  _type: Option[String],
  uniqueItems: Option[Boolean]
)

