/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiExtensionsV1beta1NetworkPolicyPeer (
  /* IPBlock defines policy on a particular IPBlock */
  ipBlock: Option[IoK8sApiExtensionsV1beta1IPBlock],
  /* Selects Namespaces using cluster scoped-labels.  This matches all pods in all namespaces selected by this label selector. This field follows standard label selector semantics. If present but empty, this selector selects all namespaces. */
  namespaceSelector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector],
  /* This is a label selector which selects Pods in this namespace. This field follows standard label selector semantics. If present but empty, this selector selects all pods in this namespace. */
  podSelector: Option[IoK8sApimachineryPkgApisMetaV1LabelSelector]
) extends ApiModel


