/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1LoadBalancerIngress (
  /* Hostname is set for load-balancer ingress points that are DNS based (typically AWS load-balancers) */
  hostname: Option[String],
  /* IP is set for load-balancer ingress points that are IP based (typically GCE or OpenStack load-balancers) */
  ip: Option[String]
)

