/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerCondition (
  /* lastTransitionTime is the last time the condition transitioned from one status to another */
  lastTransitionTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* message is a human-readable explanation containing details about the transition */
  message: Option[String],
  /* reason is the reason for the condition's last transition. */
  reason: Option[String],
  /* status is the status of the condition (True, False, Unknown) */
  status: String,
  /* type describes the current condition */
  `type`: String
) extends ApiModel


