/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiBatchV2alpha1CronJobStatus (
  /* A list of pointers to currently running jobs. */
  active: Option[Seq[IoK8sApiCoreV1ObjectReference]],
  /* Information when was the last time the job was successfully scheduled. */
  lastScheduleTime: Option[IoK8sApimachineryPkgApisMetaV1Time]
) extends ApiModel


