/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1ResourceQuotaStatus (
  /* Hard is the set of enforced hard limits for each named resource. More info: https://git.k8s.io/community/contributors/design-proposals/admission_control_resource_quota.md */
  hard: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]],
  /* Used is the current observed total usage of the resource in the namespace. */
  used: Option[Map[String, IoK8sApimachineryPkgApiResourceQuantity]]
) extends ApiModel


