/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1ContainerState (
  /* Details about a running container */
  running: Option[IoK8sApiCoreV1ContainerStateRunning],
  /* Details about a terminated container */
  terminated: Option[IoK8sApiCoreV1ContainerStateTerminated],
  /* Details about a waiting container */
  waiting: Option[IoK8sApiCoreV1ContainerStateWaiting]
)

