/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus (
  /* If request was approved, the controller will place the issued certificate here. */
  certificate: Option[String],
  /* Conditions applied to the request, such as approval or denial. */
  conditions: Option[List[IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition]]
)

