/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1Affinity (
  /* Describes node affinity scheduling rules for the pod. */
  nodeAffinity: Option[IoK8sApiCoreV1NodeAffinity],
  /* Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)). */
  podAffinity: Option[IoK8sApiCoreV1PodAffinity],
  /* Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)). */
  podAntiAffinity: Option[IoK8sApiCoreV1PodAntiAffinity]
) extends ApiModel


