/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiBatchV2alpha1CronJobSpec (
  /* Specifies how to treat concurrent executions of a Job. Defaults to Allow. */
  concurrencyPolicy: Option[String],
  /* The number of failed finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified. */
  failedJobsHistoryLimit: Option[Int],
  /* Specifies the job that will be created when executing a CronJob. */
  jobTemplate: IoK8sApiBatchV2alpha1JobTemplateSpec,
  /* The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron. */
  schedule: String,
  /* Optional deadline in seconds for starting the job if it misses scheduled time for any reason.  Missed jobs executions will be counted as failed ones. */
  startingDeadlineSeconds: Option[Long],
  /* The number of successful finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified. */
  successfulJobsHistoryLimit: Option[Int],
  /* This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.  Defaults to false. */
  suspend: Option[Boolean]
) extends ApiModel


