/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiBatchV1JobStatus (
  /* The number of actively running pods. */
  active: Option[Int],
  /* Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
  completionTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* The latest available observations of an object's current state. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/ */
  conditions: Option[Seq[IoK8sApiBatchV1JobCondition]],
  /* The number of pods which reached phase Failed. */
  failed: Option[Int],
  /* Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. */
  startTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* The number of pods which reached phase Succeeded. */
  succeeded: Option[Int]
) extends ApiModel


