/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAuthorizationV1SubjectAccessReviewSpec (
  /* Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here. */
  extra: Option[Map[String, List[String]]],
  /* Groups is the groups you're testing for. */
  groups: Option[List[String]],
  /* NonResourceAttributes describes information for a non-resource access request */
  nonResourceAttributes: Option[IoK8sApiAuthorizationV1NonResourceAttributes],
  /* ResourceAuthorizationAttributes describes information for a resource access request */
  resourceAttributes: Option[IoK8sApiAuthorizationV1ResourceAttributes],
  /* UID information about the requesting user. */
  uid: Option[String],
  /* User is the user you're testing for. If you specify \"User\" but not \"Groups\", then is it interpreted as \"What if User were not a member of any groups */
  user: Option[String]
)

