/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAutoscalingV2beta1PodsMetricSource (
  /* metricName is the name of the metric in question */
  metricName: String,
  /* targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity) */
  targetAverageValue: IoK8sApimachineryPkgApiResourceQuantity
)

