/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiBatchV1beta1CronJobSpec (
  /* Specifies how to treat concurrent executions of a Job. Defaults to Allow. */
  concurrencyPolicy: Option[String],
  /* The number of failed finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1. */
  failedJobsHistoryLimit: Option[Integer],
  /* Specifies the job that will be created when executing a CronJob. */
  jobTemplate: IoK8sApiBatchV1beta1JobTemplateSpec,
  /* The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron. */
  schedule: String,
  /* Optional deadline in seconds for starting the job if it misses scheduled time for any reason.  Missed jobs executions will be counted as failed ones. */
  startingDeadlineSeconds: Option[Long],
  /* The number of successful finished jobs to retain. This is a pointer to distinguish between explicit zero and not specified. Defaults to 3. */
  successfulJobsHistoryLimit: Option[Integer],
  /* This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.  Defaults to false. */
  suspend: Option[Boolean]
)

