/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiAppsV1beta2StatefulSetUpdateStrategy (
  /* RollingUpdate is used to communicate parameters when Type is RollingUpdateStatefulSetStrategyType. */
  rollingUpdate: Option[IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategy],
  /* Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate. */
  _type: Option[String]
)

