/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAppsV1beta1DeploymentStatus (
  /* Total number of available pods (ready for at least minReadySeconds) targeted by this deployment. */
  availableReplicas: Option[Int],
  /* Count of hash collisions for the Deployment. The Deployment controller uses this field as a collision avoidance mechanism when it needs to create the name for the newest ReplicaSet. */
  collisionCount: Option[Int],
  /* Represents the latest available observations of a deployment's current state. */
  conditions: Option[Seq[IoK8sApiAppsV1beta1DeploymentCondition]],
  /* The generation observed by the deployment controller. */
  observedGeneration: Option[Long],
  /* Total number of ready pods targeted by this deployment. */
  readyReplicas: Option[Int],
  /* Total number of non-terminated pods targeted by this deployment (their labels match the selector). */
  replicas: Option[Int],
  /* Total number of unavailable pods targeted by this deployment. This is the total number of pods that are still required for the deployment to have 100% available capacity. They may either be pods that are running but not yet available or pods that still have not been created. */
  unavailableReplicas: Option[Int],
  /* Total number of non-terminated pods targeted by this deployment that have the desired template spec. */
  updatedReplicas: Option[Int]
) extends ApiModel


