/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1ISCSIVolumeSource (
  /* whether support iSCSI Discovery CHAP authentication */
  chapAuthDiscovery: Option[Boolean],
  /* whether support iSCSI Session CHAP authentication */
  chapAuthSession: Option[Boolean],
  /* Filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: https://kubernetes.io/docs/concepts/storage/volumes#iscsi */
  fsType: Option[String],
  /* Custom iSCSI initiator name. If initiatorName is specified with iscsiInterface simultaneously, new iSCSI interface <target portal>:<volume name> will be created for the connection. */
  initiatorName: Option[String],
  /* Target iSCSI Qualified Name. */
  iqn: String,
  /* Optional: Defaults to 'default' (tcp). iSCSI interface name that uses an iSCSI transport. */
  iscsiInterface: Option[String],
  /* iSCSI target lun number. */
  lun: Int,
  /* iSCSI target portal List. The portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260). */
  portals: Option[Seq[String]],
  /* ReadOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false. */
  readOnly: Option[Boolean],
  /* CHAP secret for iSCSI target and initiator authentication */
  secretRef: Option[IoK8sApiCoreV1LocalObjectReference],
  /* iSCSI target portal. The portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260). */
  targetPortal: String
) extends ApiModel


