/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1EnvFromSource (
  /* The ConfigMap to select from */
  configMapRef: Option[IoK8sApiCoreV1ConfigMapEnvSource],
  /* An optional identifer to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER. */
  prefix: Option[String],
  /* The Secret to select from */
  secretRef: Option[IoK8sApiCoreV1SecretEnvSource]
)

