/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionSpec (
  /* Group is the group this resource belongs in */
  group: String,
  /* Names are the names used to describe this custom resource */
  names: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames,
  /* Scope indicates whether this resource is cluster or namespace scoped.  Default is namespaced */
  scope: String,
  /* Validation describes the validation methods for CustomResources This field is alpha-level and should only be sent to servers that enable the CustomResourceValidation feature. */
  validation: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation],
  /* Version is the version this resource belongs in */
  version: String
) extends ApiModel


