/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1NodeSpec (
  /* If specified, the source to get node configuration from The DynamicKubeletConfig feature gate must be enabled for the Kubelet to use this field */
  configSource: Option[IoK8sApiCoreV1NodeConfigSource],
  /* External ID of the node assigned by some machine database (e.g. a cloud provider). Deprecated. */
  externalID: Option[String],
  /* PodCIDR represents the pod IP range assigned to the node. */
  podCIDR: Option[String],
  /* ID of the node assigned by the cloud provider in the format: <ProviderName>://<ProviderSpecificNodeID> */
  providerID: Option[String],
  /* If specified, the node's taints. */
  taints: Option[List[IoK8sApiCoreV1Taint]],
  /* Unschedulable controls node schedulability of new pods. By default, node is schedulable. More info: https://kubernetes.io/docs/concepts/nodes/node/#manual-node-administration */
  unschedulable: Option[Boolean]
)

