/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1PodCondition (
  /* Last time we probed the condition. */
  lastProbeTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Last time the condition transitioned from one status to another. */
  lastTransitionTime: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Human-readable message indicating details about last transition. */
  message: Option[String],
  /* Unique, one-word, CamelCase reason for the condition's last transition. */
  reason: Option[String],
  /* Status is the status of the condition. Can be True, False, Unknown. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions */
  status: String,
  /* Type is the type of the condition. Currently only Ready. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions */
  _type: String
)

