/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames (
  /* Kind is the serialized kind of the resource.  It is normally CamelCase and singular. */
  kind: String,
  /* ListKind is the serialized kind of the list for this resource.  Defaults to <kind>List. */
  listKind: Option[String],
  /* Plural is the plural name of the resource to serve.  It must match the name of the CustomResourceDefinition-registration too: plural.group and it must be all lowercase. */
  plural: String,
  /* ShortNames are short names for the resource.  It must be all lowercase. */
  shortNames: Option[List[String]],
  /* Singular is the singular name of the resource.  It must be all lowercase  Defaults to lowercased <kind> */
  singular: Option[String]
)

