/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiAuthorizationV1SubjectAccessReviewSpec (
  /* Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here. */
  extra: Option[Map[String, Seq[String]]],
  /* Groups is the groups you're testing for. */
  groups: Option[Seq[String]],
  /* NonResourceAttributes describes information for a non-resource access request */
  nonResourceAttributes: Option[IoK8sApiAuthorizationV1NonResourceAttributes],
  /* ResourceAuthorizationAttributes describes information for a resource access request */
  resourceAttributes: Option[IoK8sApiAuthorizationV1ResourceAttributes],
  /* UID information about the requesting user. */
  uid: Option[String],
  /* User is the user you're testing for. If you specify \"User\" but not \"Groups\", then is it interpreted as \"What if User were not a member of any groups */
  user: Option[String]
) extends ApiModel


