/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1Handler (
  /* One and only one of the following should be specified. Exec specifies the action to take. */
  exec: Option[IoK8sApiCoreV1ExecAction],
  /* HTTPGet specifies the http request to perform. */
  httpGet: Option[IoK8sApiCoreV1HTTPGetAction],
  /* TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported */
  tcpSocket: Option[IoK8sApiCoreV1TCPSocketAction]
) extends ApiModel


