/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1VolumeMount (
  /* Path within the container at which the volume should be mounted.  Must not contain ':'. */
  mountPath: String,
  /* mountPropagation determines how mounts are propagated from the host to container and the other way around. When not set, MountPropagationHostToContainer is used. This field is alpha in 1.8 and can be reworked or removed in a future release. */
  mountPropagation: Option[String],
  /* This must match the Name of a Volume. */
  name: String,
  /* Mounted read-only if true, read-write otherwise (false or unspecified). Defaults to false. */
  readOnly: Option[Boolean],
  /* Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root). */
  subPath: Option[String]
)

