/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1Event (
  /* APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources */
  apiVersion: Option[String],
  /* The number of times this event has occurred. */
  count: Option[Int],
  /* The time at which the event was first recorded. (Time of server receipt is in TypeMeta.) */
  firstTimestamp: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* The object that this event is about. */
  involvedObject: IoK8sApiCoreV1ObjectReference,
  /* Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds */
  kind: Option[String],
  /* The time at which the most recent occurrence of this event was recorded. */
  lastTimestamp: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* A human-readable description of the status of this operation. */
  message: Option[String],
  /* Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata */
  metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta,
  /* This should be a short, machine understandable string that gives the reason for the transition into the object's current status. */
  reason: Option[String],
  /* The component reporting this event. Should be a short machine understandable string. */
  source: Option[IoK8sApiCoreV1EventSource],
  /* Type of this event (Normal, Warning), new types could be added in the future */
  `type`: Option[String]
) extends ApiModel


