/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1Taint (
  /* Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute. */
  effect: String,
  /* Required. The taint key to be applied to a node. */
  key: String,
  /* TimeAdded represents the time at which the taint was added. It is only written for NoExecute taints. */
  timeAdded: Option[IoK8sApimachineryPkgApisMetaV1Time],
  /* Required. The taint value corresponding to the taint key. */
  value: Option[String]
)

