/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation (
  /* OpenAPIV3Schema is the OpenAPI v3 schema to be validated against. */
  openAPIV3Schema: Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps]
)

