/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApimachineryPkgApisMetaV1LabelSelector (
  /* matchExpressions is a list of label selector requirements. The requirements are ANDed. */
  matchExpressions: Option[Seq[IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement]],
  /* matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed. */
  matchLabels: Option[Map[String, String]]
) extends ApiModel


