/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class IoK8sApiCoreV1PersistentVolumeStatus (
  /* A human-readable message indicating details about why the volume is in this state. */
  message: Option[String],
  /* Phase indicates if a volume is available, bound to a claim, or released by a claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#phase */
  phase: Option[String],
  /* Reason is a brief CamelCase string that describes any failure and is meant for machine parsing and tidy display in the CLI. */
  reason: Option[String]
)

