/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class IoK8sApiCoreV1EndpointSubset (
  /* IP addresses which offer the related ports that are marked as ready. These endpoints should be considered safe for load balancers and clients to utilize. */
  addresses: Option[Seq[IoK8sApiCoreV1EndpointAddress]],
  /* IP addresses which offer the related ports but are not currently marked as ready because they have not yet finished starting, have recently failed a readiness check, or have recently failed a liveness check. */
  notReadyAddresses: Option[Seq[IoK8sApiCoreV1EndpointAddress]],
  /* Port numbers available on the related IP addresses. */
  ports: Option[Seq[IoK8sApiCoreV1EndpointPort]]
) extends ApiModel


