/**
 * Kubernetes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.9.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api

import io.swagger.client.model.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
import io.swagger.client.model.IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1DeleteOptions
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Patch
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Status
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1WatchEvent
import io.swagger.client.ApiInvoker
import io.swagger.client.ApiException

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date

import scala.collection.mutable.HashMap

class Apiextensions_v1beta1Api(val defBasePath: String = "https://localhost",
                        defApiInvoker: ApiInvoker = ApiInvoker) {
  var basePath = defBasePath
  var apiInvoker = defApiInvoker

  def addHeader(key: String, value: String) = apiInvoker.defaultHeaders += key -> value 

  /**
   * 
   * create a CustomResourceDefinition
   * @param body  
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
   */
  def createApiextensionsV1beta1CustomResourceDefinition(body: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition, pretty: Option[String] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions".replaceAll("\\{format\\}", "json")

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (body == null) throw new Exception("Missing required parameter 'body' when calling Apiextensions_v1beta1Api->createApiextensionsV1beta1CustomResourceDefinition")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    

    var postBody: AnyRef = body

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "POST", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * delete collection of CustomResourceDefinition
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications. (optional)
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything. (optional)
   * @param includeUninitialized If true, partially initialized resources are included in the response. (optional)
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything. (optional)
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv. (optional)
   * @param timeoutSeconds Timeout for the list/watch call. (optional)
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. (optional)
   * @return IoK8sApimachineryPkgApisMetaV1Status
   */
  def deleteApiextensionsV1beta1CollectionCustomResourceDefinition(pretty: Option[String] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Integer] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Integer] = None, watch: Option[Boolean] = None): Option[IoK8sApimachineryPkgApisMetaV1Status] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions".replaceAll("\\{format\\}", "json")

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    continue.map(paramVal => queryParams += "continue" -> paramVal.toString)
    fieldSelector.map(paramVal => queryParams += "fieldSelector" -> paramVal.toString)
    includeUninitialized.map(paramVal => queryParams += "includeUninitialized" -> paramVal.toString)
    labelSelector.map(paramVal => queryParams += "labelSelector" -> paramVal.toString)
    limit.map(paramVal => queryParams += "limit" -> paramVal.toString)
    resourceVersion.map(paramVal => queryParams += "resourceVersion" -> paramVal.toString)
    timeoutSeconds.map(paramVal => queryParams += "timeoutSeconds" -> paramVal.toString)
    watch.map(paramVal => queryParams += "watch" -> paramVal.toString)
    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "DELETE", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApimachineryPkgApisMetaV1Status]).asInstanceOf[IoK8sApimachineryPkgApisMetaV1Status])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * delete a CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param body  
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately. (optional)
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \&quot;orphan\&quot; finalizer will be added to/removed from the object&#39;s finalizers list. Either this field or PropagationPolicy may be set, but not both. (optional)
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. (optional)
   * @return IoK8sApimachineryPkgApisMetaV1Status
   */
  def deleteApiextensionsV1beta1CustomResourceDefinition(name: String, body: IoK8sApimachineryPkgApisMetaV1DeleteOptions, pretty: Option[String] = None, gracePeriodSeconds: Option[Integer] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None): Option[IoK8sApimachineryPkgApisMetaV1Status] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->deleteApiextensionsV1beta1CustomResourceDefinition")

    if (body == null) throw new Exception("Missing required parameter 'body' when calling Apiextensions_v1beta1Api->deleteApiextensionsV1beta1CustomResourceDefinition")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    gracePeriodSeconds.map(paramVal => queryParams += "gracePeriodSeconds" -> paramVal.toString)
    orphanDependents.map(paramVal => queryParams += "orphanDependents" -> paramVal.toString)
    propagationPolicy.map(paramVal => queryParams += "propagationPolicy" -> paramVal.toString)
    

    var postBody: AnyRef = body

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "DELETE", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApimachineryPkgApisMetaV1Status]).asInstanceOf[IoK8sApimachineryPkgApisMetaV1Status])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * get available resources
   * @return IoK8sApimachineryPkgApisMetaV1APIResourceList
   */
  def getApiextensionsV1beta1APIResources(): Option[IoK8sApimachineryPkgApisMetaV1APIResourceList] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/".replaceAll("\\{format\\}", "json")

    val contentTypes = List("application/json", "application/yaml", "application/vnd.kubernetes.protobuf")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApimachineryPkgApisMetaV1APIResourceList]).asInstanceOf[IoK8sApimachineryPkgApisMetaV1APIResourceList])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * list or watch objects of kind CustomResourceDefinition
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications. (optional)
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything. (optional)
   * @param includeUninitialized If true, partially initialized resources are included in the response. (optional)
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything. (optional)
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv. (optional)
   * @param timeoutSeconds Timeout for the list/watch call. (optional)
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList
   */
  def listApiextensionsV1beta1CustomResourceDefinition(pretty: Option[String] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Integer] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Integer] = None, watch: Option[Boolean] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions".replaceAll("\\{format\\}", "json")

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    continue.map(paramVal => queryParams += "continue" -> paramVal.toString)
    fieldSelector.map(paramVal => queryParams += "fieldSelector" -> paramVal.toString)
    includeUninitialized.map(paramVal => queryParams += "includeUninitialized" -> paramVal.toString)
    labelSelector.map(paramVal => queryParams += "labelSelector" -> paramVal.toString)
    limit.map(paramVal => queryParams += "limit" -> paramVal.toString)
    resourceVersion.map(paramVal => queryParams += "resourceVersion" -> paramVal.toString)
    timeoutSeconds.map(paramVal => queryParams += "timeoutSeconds" -> paramVal.toString)
    watch.map(paramVal => queryParams += "watch" -> paramVal.toString)
    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * partially update the specified CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param body  
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
   */
  def patchApiextensionsV1beta1CustomResourceDefinition(name: String, body: IoK8sApimachineryPkgApisMetaV1Patch, pretty: Option[String] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("application/json-patch+json", "application/merge-patch+json", "application/strategic-merge-patch+json")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->patchApiextensionsV1beta1CustomResourceDefinition")

    if (body == null) throw new Exception("Missing required parameter 'body' when calling Apiextensions_v1beta1Api->patchApiextensionsV1beta1CustomResourceDefinition")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    

    var postBody: AnyRef = body

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "PATCH", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * read the specified CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like &#39;Namespace&#39;. (optional)
   * @param export Should this value be exported.  Export strips fields that a user can not specify. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
   */
  def readApiextensionsV1beta1CustomResourceDefinition(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->readApiextensionsV1beta1CustomResourceDefinition")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    exact.map(paramVal => queryParams += "exact" -> paramVal.toString)
    export.map(paramVal => queryParams += "export" -> paramVal.toString)
    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * replace the specified CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param body  
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
   */
  def replaceApiextensionsV1beta1CustomResourceDefinition(name: String, body: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition, pretty: Option[String] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->replaceApiextensionsV1beta1CustomResourceDefinition")

    if (body == null) throw new Exception("Missing required parameter 'body' when calling Apiextensions_v1beta1Api->replaceApiextensionsV1beta1CustomResourceDefinition")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    

    var postBody: AnyRef = body

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "PUT", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * replace status of the specified CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param body  
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @return IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
   */
  def replaceApiextensionsV1beta1CustomResourceDefinitionStatus(name: String, body: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition, pretty: Option[String] = None): Option[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/{name}/status".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->replaceApiextensionsV1beta1CustomResourceDefinitionStatus")

    if (body == null) throw new Exception("Missing required parameter 'body' when calling Apiextensions_v1beta1Api->replaceApiextensionsV1beta1CustomResourceDefinitionStatus")

    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    

    var postBody: AnyRef = body

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "PUT", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition]).asInstanceOf[IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * watch changes to an object of kind CustomResourceDefinition
   * @param name name of the CustomResourceDefinition 
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications. (optional)
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything. (optional)
   * @param includeUninitialized If true, partially initialized resources are included in the response. (optional)
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything. (optional)
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv. (optional)
   * @param timeoutSeconds Timeout for the list/watch call. (optional)
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. (optional)
   * @return IoK8sApimachineryPkgApisMetaV1WatchEvent
   */
  def watchApiextensionsV1beta1CustomResourceDefinition(name: String, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Integer] = None, pretty: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Integer] = None, watch: Option[Boolean] = None): Option[IoK8sApimachineryPkgApisMetaV1WatchEvent] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/watch/customresourcedefinitions/{name}".replaceAll("\\{format\\}", "json").replaceAll("\\{" + "name" + "\\}",apiInvoker.escape(name))

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (name == null) throw new Exception("Missing required parameter 'name' when calling Apiextensions_v1beta1Api->watchApiextensionsV1beta1CustomResourceDefinition")

    continue.map(paramVal => queryParams += "continue" -> paramVal.toString)
    fieldSelector.map(paramVal => queryParams += "fieldSelector" -> paramVal.toString)
    includeUninitialized.map(paramVal => queryParams += "includeUninitialized" -> paramVal.toString)
    labelSelector.map(paramVal => queryParams += "labelSelector" -> paramVal.toString)
    limit.map(paramVal => queryParams += "limit" -> paramVal.toString)
    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    resourceVersion.map(paramVal => queryParams += "resourceVersion" -> paramVal.toString)
    timeoutSeconds.map(paramVal => queryParams += "timeoutSeconds" -> paramVal.toString)
    watch.map(paramVal => queryParams += "watch" -> paramVal.toString)
    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApimachineryPkgApisMetaV1WatchEvent]).asInstanceOf[IoK8sApimachineryPkgApisMetaV1WatchEvent])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

  /**
   * 
   * watch individual changes to a list of CustomResourceDefinition
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications. (optional)
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything. (optional)
   * @param includeUninitialized If true, partially initialized resources are included in the response. (optional)
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything. (optional)
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned. (optional)
   * @param pretty If &#39;true&#39;, then the output is pretty printed. (optional)
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv. (optional)
   * @param timeoutSeconds Timeout for the list/watch call. (optional)
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion. (optional)
   * @return IoK8sApimachineryPkgApisMetaV1WatchEvent
   */
  def watchApiextensionsV1beta1CustomResourceDefinitionList(continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Integer] = None, pretty: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Integer] = None, watch: Option[Boolean] = None): Option[IoK8sApimachineryPkgApisMetaV1WatchEvent] = {
    // create path and map variables
    val path = "/apis/apiextensions.k8s.io/v1beta1/watch/customresourcedefinitions".replaceAll("\\{format\\}", "json")

    val contentTypes = List("*/*")
    val contentType = contentTypes(0)

    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    continue.map(paramVal => queryParams += "continue" -> paramVal.toString)
    fieldSelector.map(paramVal => queryParams += "fieldSelector" -> paramVal.toString)
    includeUninitialized.map(paramVal => queryParams += "includeUninitialized" -> paramVal.toString)
    labelSelector.map(paramVal => queryParams += "labelSelector" -> paramVal.toString)
    limit.map(paramVal => queryParams += "limit" -> paramVal.toString)
    pretty.map(paramVal => queryParams += "pretty" -> paramVal.toString)
    resourceVersion.map(paramVal => queryParams += "resourceVersion" -> paramVal.toString)
    timeoutSeconds.map(paramVal => queryParams += "timeoutSeconds" -> paramVal.toString)
    watch.map(paramVal => queryParams += "watch" -> paramVal.toString)
    

    var postBody: AnyRef = null

    if (contentType.startsWith("multipart/form-data")) {
      val mp = new FormDataMultiPart
      postBody = mp
    } else {
    }

    try {
      apiInvoker.invokeApi(basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType) match {
        case s: String =>
           Some(apiInvoker.deserialize(s, "", classOf[IoK8sApimachineryPkgApisMetaV1WatchEvent]).asInstanceOf[IoK8sApimachineryPkgApisMetaV1WatchEvent])
        case _ => None
      }
    } catch {
      case ex: ApiException if ex.code == 404 => None
      case ex: ApiException => throw ex
    }
  }

}
