/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIGroup
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object ApiextensionsApi {

  /**
   * get information of a group
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1APIGroup (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def getApiextensionsAPIGroup()(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1APIGroup] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1APIGroup](ApiMethods.GET, "https://localhost", "/apis/apiextensions.k8s.io/", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1APIGroup](200)
      .withErrorResponse[Unit](401)
      

}

