/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.IoK8sApiStorageV1StorageClass
import io.swagger.client.model.IoK8sApiStorageV1StorageClassList
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1APIResourceList
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1DeleteOptions
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Patch
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1Status
import io.swagger.client.model.IoK8sApimachineryPkgApisMetaV1WatchEvent
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object Storage_v1Api {

  /**
   * create a StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApiStorageV1StorageClass (OK)
   *   code 201 : IoK8sApiStorageV1StorageClass (Created)
   *   code 202 : IoK8sApiStorageV1StorageClass (Accepted)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param body 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   */
  def createStorageV1StorageClass(body: IoK8sApiStorageV1StorageClass, pretty: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApiStorageV1StorageClass] =
    ApiRequest[IoK8sApiStorageV1StorageClass](ApiMethods.POST, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withBody(body)
      .withQueryParam("pretty", pretty)
      .withSuccessResponse[IoK8sApiStorageV1StorageClass](200)
      .withErrorResponse[IoK8sApiStorageV1StorageClass](201)
      .withErrorResponse[IoK8sApiStorageV1StorageClass](202)
      .withErrorResponse[Unit](401)
        /**
   * delete collection of StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param includeUninitialized If true, partially initialized resources are included in the response.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def deleteStorageV1CollectionStorageClass(pretty: Option[String] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1Status] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1Status](ApiMethods.DELETE, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withQueryParam("pretty", pretty)
      .withQueryParam("continue", continue)
      .withQueryParam("fieldSelector", fieldSelector)
      .withQueryParam("includeUninitialized", includeUninitialized)
      .withQueryParam("labelSelector", labelSelector)
      .withQueryParam("limit", limit)
      .withQueryParam("resourceVersion", resourceVersion)
      .withQueryParam("timeoutSeconds", timeoutSeconds)
      .withQueryParam("watch", watch)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1Status](200)
      .withErrorResponse[Unit](401)
        /**
   * delete a StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1Status (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param body 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the \&quot;orphan\&quot; finalizer will be added to/removed from the object&#39;s finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy.
   */
  def deleteStorageV1StorageClass(name: String, body: IoK8sApimachineryPkgApisMetaV1DeleteOptions, pretty: Option[String] = None, gracePeriodSeconds: Option[Int] = None, orphanDependents: Option[Boolean] = None, propagationPolicy: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1Status] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1Status](ApiMethods.DELETE, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses/{name}", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withBody(body)
      .withQueryParam("pretty", pretty)
      .withQueryParam("gracePeriodSeconds", gracePeriodSeconds)
      .withQueryParam("orphanDependents", orphanDependents)
      .withQueryParam("propagationPolicy", propagationPolicy)
      .withPathParam("name", name)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1Status](200)
      .withErrorResponse[Unit](401)
        /**
   * get available resources
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1APIResourceList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   */
  def getStorageV1APIResources()(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1APIResourceList] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1APIResourceList](ApiMethods.GET, "https://localhost", "/apis/storage.k8s.io/v1/", "application/json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1APIResourceList](200)
      .withErrorResponse[Unit](401)
        /**
   * list or watch objects of kind StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApiStorageV1StorageClassList (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param includeUninitialized If true, partially initialized resources are included in the response.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def listStorageV1StorageClass(pretty: Option[String] = None, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApiStorageV1StorageClassList] =
    ApiRequest[IoK8sApiStorageV1StorageClassList](ApiMethods.GET, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withQueryParam("pretty", pretty)
      .withQueryParam("continue", continue)
      .withQueryParam("fieldSelector", fieldSelector)
      .withQueryParam("includeUninitialized", includeUninitialized)
      .withQueryParam("labelSelector", labelSelector)
      .withQueryParam("limit", limit)
      .withQueryParam("resourceVersion", resourceVersion)
      .withQueryParam("timeoutSeconds", timeoutSeconds)
      .withQueryParam("watch", watch)
      .withSuccessResponse[IoK8sApiStorageV1StorageClassList](200)
      .withErrorResponse[Unit](401)
        /**
   * partially update the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApiStorageV1StorageClass (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param body 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   */
  def patchStorageV1StorageClass(name: String, body: IoK8sApimachineryPkgApisMetaV1Patch, pretty: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApiStorageV1StorageClass] =
    ApiRequest[IoK8sApiStorageV1StorageClass](ApiMethods.PATCH, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses/{name}", "application/json-patch+json")
      .withApiKey(apiKey, "authorization", HEADER)
      .withBody(body)
      .withQueryParam("pretty", pretty)
      .withPathParam("name", name)
      .withSuccessResponse[IoK8sApiStorageV1StorageClass](200)
      .withErrorResponse[Unit](401)
        /**
   * read the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApiStorageV1StorageClass (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like &#39;Namespace&#39;.
   * @param export Should this value be exported.  Export strips fields that a user can not specify.
   */
  def readStorageV1StorageClass(name: String, pretty: Option[String] = None, exact: Option[Boolean] = None, export: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApiStorageV1StorageClass] =
    ApiRequest[IoK8sApiStorageV1StorageClass](ApiMethods.GET, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses/{name}", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withQueryParam("pretty", pretty)
      .withQueryParam("exact", exact)
      .withQueryParam("export", export)
      .withPathParam("name", name)
      .withSuccessResponse[IoK8sApiStorageV1StorageClass](200)
      .withErrorResponse[Unit](401)
        /**
   * replace the specified StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApiStorageV1StorageClass (OK)
   *   code 201 : IoK8sApiStorageV1StorageClass (Created)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param body 
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   */
  def replaceStorageV1StorageClass(name: String, body: IoK8sApiStorageV1StorageClass, pretty: Option[String] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApiStorageV1StorageClass] =
    ApiRequest[IoK8sApiStorageV1StorageClass](ApiMethods.PUT, "https://localhost", "/apis/storage.k8s.io/v1/storageclasses/{name}", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withBody(body)
      .withQueryParam("pretty", pretty)
      .withPathParam("name", name)
      .withSuccessResponse[IoK8sApiStorageV1StorageClass](200)
      .withErrorResponse[IoK8sApiStorageV1StorageClass](201)
      .withErrorResponse[Unit](401)
        /**
   * watch changes to an object of kind StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1WatchEvent (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param name name of the StorageClass
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param includeUninitialized If true, partially initialized resources are included in the response.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def watchStorageV1StorageClass(name: String, continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, pretty: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1WatchEvent] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1WatchEvent](ApiMethods.GET, "https://localhost", "/apis/storage.k8s.io/v1/watch/storageclasses/{name}", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withQueryParam("continue", continue)
      .withQueryParam("fieldSelector", fieldSelector)
      .withQueryParam("includeUninitialized", includeUninitialized)
      .withQueryParam("labelSelector", labelSelector)
      .withQueryParam("limit", limit)
      .withQueryParam("pretty", pretty)
      .withQueryParam("resourceVersion", resourceVersion)
      .withQueryParam("timeoutSeconds", timeoutSeconds)
      .withQueryParam("watch", watch)
      .withPathParam("name", name)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1WatchEvent](200)
      .withErrorResponse[Unit](401)
        /**
   * watch individual changes to a list of StorageClass
   * 
   * Expected answers:
   *   code 200 : IoK8sApimachineryPkgApisMetaV1WatchEvent (OK)
   *   code 401 :  (Unauthorized)
   * 
   * Available security schemes:
   *   BearerToken (apiKey)
   * 
   * @param continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server the server will respond with a 410 ResourceExpired error indicating the client must restart their list without the continue field. This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param includeUninitialized If true, partially initialized resources are included in the response.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  def watchStorageV1StorageClassList(continue: Option[String] = None, fieldSelector: Option[String] = None, includeUninitialized: Option[Boolean] = None, labelSelector: Option[String] = None, limit: Option[Int] = None, pretty: Option[String] = None, resourceVersion: Option[String] = None, timeoutSeconds: Option[Int] = None, watch: Option[Boolean] = None)(implicit apiKey: ApiKeyValue): ApiRequest[IoK8sApimachineryPkgApisMetaV1WatchEvent] =
    ApiRequest[IoK8sApimachineryPkgApisMetaV1WatchEvent](ApiMethods.GET, "https://localhost", "/apis/storage.k8s.io/v1/watch/storageclasses", "*/*")
      .withApiKey(apiKey, "authorization", HEADER)
      .withQueryParam("continue", continue)
      .withQueryParam("fieldSelector", fieldSelector)
      .withQueryParam("includeUninitialized", includeUninitialized)
      .withQueryParam("labelSelector", labelSelector)
      .withQueryParam("limit", limit)
      .withQueryParam("pretty", pretty)
      .withQueryParam("resourceVersion", resourceVersion)
      .withQueryParam("timeoutSeconds", timeoutSeconds)
      .withQueryParam("watch", watch)
      .withSuccessResponse[IoK8sApimachineryPkgApisMetaV1WatchEvent](200)
      .withErrorResponse[Unit](401)
      

}

